global using EfCoreDto.Core.Common;
global using EfCoreDto.Core.DTOs;
global using EfCoreDto.Core.Eums;
global using EfCoreDto.Core.Exceptions;
global using EfCoreDto.Core.Services;
global using EfCoreDto.WebApi.Endpoints;
global using EfCoreDto.WebApi.Extensions;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Options;
global using static Microsoft.AspNetCore.Http.StatusCodes;
